apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:9.4
      env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"